name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' #

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: setup chrome
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          python main.py
          git add .
          git commit -m "update wallets.txt"
